import type { Destination } from "@/types";

export const destinations: Destination[] = [
  {
    id: "usa",
    name: "USA",
    tagline: "World-leading research universities and flexible liberal arts pathways.",
    highlights: ["Ivy & top-50 options", "SAT/ACT pathways", "Merit scholarships"],
    bestFor: "Students seeking flexible pathways, research depth, and broad scholarship ecosystems.",
    considerations: "Higher cost of attendance; plan testing, essays, and funding early.",
    visualLabel: "Research university campus",
    theme: "usa",
  },
  {
    id: "uk",
    name: "UK",
    tagline: "Focused degrees at globally ranked institutions.",
    highlights: ["UCAS applications", "3-year honours", "Russell Group targets"],
    bestFor: "Focused degree paths and globally recognized institutions in shorter timelines.",
    considerations: "Competitive entry for top courses; align academics and subject fit closely.",
    visualLabel: "Historic university campus",
    theme: "uk",
  },
  {
    id: "canada",
    name: "Canada",
    tagline: "High-quality education with strong post-study pathways.",
    highlights: ["Co-op programs", "PR-friendly", "Affordable public universities"],
    bestFor: "Families prioritizing quality, affordability, and post-study pathways.",
    considerations: "Winter climate and regional campus choice affect lifestyle fit.",
    visualLabel: "Modern student city",
    theme: "canada",
  },
  {
    id: "australia",
    name: "Australia",
    tagline: "Innovation-driven campuses in vibrant student cities.",
    highlights: ["Group of Eight", "Work rights", "February & July intakes"],
    bestFor: "Students who want innovation, work rights, and vibrant campus cities.",
    considerations: "Distance and intake timing require forward planning.",
    visualLabel: "Innovation campus",
    theme: "australia",
  },
  {
    id: "germany",
    name: "Germany",
    tagline: "Engineering excellence with accessible public university options.",
    highlights: ["Low tuition public unis", "English-taught programs", "Strong STEM"],
    bestFor: "STEM-focused students exploring strong public universities and practical training.",
    considerations: "Language and program format vary; confirm English-taught options early.",
    visualLabel: "Engineering university hub",
    theme: "germany",
  },
  {
    id: "france",
    name: "France",
    tagline: "Prestigious grandes écoles and creative industry hubs.",
    highlights: ["Business & design", "English programs", "Cultural depth"],
    bestFor: "Creative, business, and specialist programs with European cultural depth.",
    considerations: "Program selectivity and language expectations differ by school.",
    visualLabel: "Creative & business campus",
    theme: "france",
  },
  {
    id: "uae",
    name: "UAE",
    tagline: "Global branch campuses and fast-growing regional hubs.",
    highlights: ["International campuses", "Business & tech", "Gateway to Asia"],
    bestFor: "Students seeking international branch campuses and regional business hubs.",
    considerations: "Compare accreditation, outcomes, and long-term mobility goals.",
    visualLabel: "Global branch campus hub",
    theme: "uae",
  },
  {
    id: "singapore",
    name: "Singapore",
    tagline: "Asia's academic powerhouse with world-class outcomes.",
    highlights: ["NUS & NTU", "Finance & tech", "Safe, global city"],
    bestFor: "High-achievers targeting rigorous academics in a global city campus.",
    considerations: "Competitive admits; build a strong, well-rounded profile.",
    visualLabel: "Modern city-campus",
    theme: "singapore",
  },
];

export const featuredDestinationIds = ["usa", "uk"] as const;
